services:

  mongodb:
    image: mongo:4.2.3-bionic
    restart: always
    volumes:
      - mongodb_data:/data/db
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - expense-tracker-network

  # Auth Service Components
  auth-db:
    image: postgres:12
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d auth_service"]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 30s
    volumes:
      - auth-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .auth-service.env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=auth_service
    networks:
      - expense-tracker-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  auth-prestart:
    image: sali72/auth-service:latest
    networks:
      - expense-tracker-network
    depends_on:
      auth-db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart.sh
    env_file:
      - .auth-service.env
    environment:
      - POSTGRES_SERVER=auth-db
      - POSTGRES_PORT=5432

  auth-service:
    container_name: auth-service
    image: sali72/auth-service:latest
    restart: always
    # For development
    command: fastapi dev app/main.py --host 0.0.0.0 --root-path /auth-service
    networks:
      - expense-tracker-network
    depends_on:
      auth-db:
        condition: service_healthy
        restart: true
      auth-prestart:
        condition: service_completed_successfully
    env_file:
      - .auth-service.env
    environment:
      - POSTGRES_SERVER=auth-db
      - POSTGRES_PORT=5432
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  expense-tracker:
    image: expense-tracker
    build:
      context: .
    # ports:
    #   - 8000:8000
    
    # For development {
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests
    command: fastapi dev --host 0.0.0.0 --reload app/main.py --root-path /expense-tracker
    # } For development
    environment:
      - AUTH_SERVICE_URL=http://auth-service:8000
    env_file:
      - .env
    depends_on:
      - mongodb
      - auth-service
    networks:
      - expense-tracker-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - expense-tracker
    networks:
      - expense-tracker-network

networks:
  expense-tracker-network:

volumes:
  mongodb_data:
  auth-db-data:
